### PR TITLE
Fixes constant diff for Cortex rules that have boolean labels and annotations

### LINKED ISSUE #13: Plan including `cortex_rules` with boolean labels/annotations always show changes
## Observed

I have observed TF plans showing diffs even when the resource `cortex_rule` has not been modified.

## Details

This seems to be due to the implementation of `DiffSuppressFunc`:

* A rule's `content` is a YAML string that can include booleans, i.e a value of `true`
* `cortex_rule` field `content` is a YAML string marshalled into `rwrulefmt.RuleGroup`
* `labels` and `annotations` in `rwrulefmt.RuleGroup` are `map[string]string`
* When marshalling a rule file into `rwrulefmt.RuleGroup` its `labels` and `annotations` are interpreted as a `string` regardless of whether the input is a boolean
* When `suppressYAMLDiff` compares new and old rules it marshals and unmarshals which takes cares of formatting differences. However, when the rule's `content` field from latest TF (new) is compared against the `content` field from state (old), for booleans, it receives the values `true` and `"true"` respectively. 

## Suggested fix

Instead of comparing strings, the `DiffSuppressFunc` implementation could compare rules using Prometheus' own rule comparison functions.

### PR DESCRIPTION
**Pull request by janakerman-form3**
Fixes https://github.com/inuits/terraform-provider-cortex/issues/13

Changes mainly picked from this pull request (https://github.com/form3tech-oss/terraform-provider-cortex/pull/3) to keep the PR as small as possible (additional contributions can be considered as separate PRs):

* Updates `DiffSurpressFunc` implementation to compare using rule group structs
* Adds local Cortex setup 
* Adds acceptance tests that run against local Cortex, including failing test regression test covering the bug
* Changes to Makefile
  * Adds Makefile targets for local dev
  * Adds `.PHONY` Makefile targets
  * Simplifies `go test` commands
* Updates README

### CODE REVIEW

**Comment by janakerman** [comment]
@roidelapluie @carroarmato0 - I hope it's not too rude to ping you directly on this?

**Comment by roidelapluie** [comment]
This seems fragile to me, I am not sure we should go as far as this. What would cause a diff ? I am afraid that we would be to tied up with some versions of cortex/prometheus.

**Comment by roidelapluie** [comment]
Can you isolate the rules fixes? makefiles etc are standard terraform, so we would need to align that with upstream instead of changing them downstream.

**Comment by janakerman-form3** [comment]
> makefiles etc are standard terraform

I'm not sure I fully understand what you mean here. Do you have an example of the standard Makefile that a provider should follow? (A colleague pointed me at [this](https://github.com/hashicorp/terraform-provider-scaffolding) but this provider already differs from this skaffolding 🤔 ).

The only issue with removing _all_ of the Makefile changes is that the acceptance tests need a Cortex instance to run. The makefile targets `cortex-up` and `cortex-down` set up these acceptance test dependencies (run by the `testacc` target).

**Comment by roidelapluie** [comment]
Okay, let's go for this, thanks!

**Comment by roidelapluie** [comment]
I have tagged v0.0.4

**Pull request merged**
